apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-namespace

resources:
  - Namespace.yaml
  - Postgres-deployment.yaml
  - Fastapi-deployment.yaml

secretGenerator:
  - name: db-creds
    envs:
      - db-creds.env