name: Flask Ci workflow 

on:
  push:
    branches: [ "main" ]
    paths:
      - '02-backend-app-statefulset/api-flask/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./02-backend-app-statefulset/api-flask

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" 

      # 2. Run unittest
      - name: Install dependency
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Set PYTHONPATH so python can find the 'src' module
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          python3 -m unittest discover -v -s tests

