name: Flask Ci workflow 

on:
  push:
    branches: [ "main" ]
    paths:
      - '02-backend-app-statefulset/api-flask/**'

jobs:
  linting-and-formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./02-backend-app-statefulset/api-flask

    steps:
        - uses: actions/checkout@v5
        - name: Install Ruff
          run: pip install ruff
        - name: Lint with Ruff
          run: ruff check .
  
  unit-tests:
    needs: linting-and-formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./02-backend-app-statefulset/api-flask
    steps:
      - uses: actions/checkout@v5
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.19"
          cache: 'pip'
      - name: install dependencies
        run: pip install -r requirements.txt 
      - name: run tests
        run: pytest
